import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '@layout/Navbar';
import Hero from '@organisms/Hero';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
    </>
  );
};

export default Home;
