export default {
  green: {
    text: 'text-green-50',
    background: 'bg-green-500',
    hover: 'hover:bg-green-600',
    focus: 'focus:border-green-200',
    disabled: 'disabled:bg-green-300',
    outline: 'border border-green-500 bg-transparent text-green-500',
    soft: 'bg-green-200 text-green-500',
    minimal: 'bg-transparent text-green-500',
  },
  blue: {
    text: 'text-blue-50',
    background: 'bg-blue-500',
    hover: 'hover:bg-blue-600',
    focus: 'focus:border-blue-200',
    disabled: 'disabled:bg-blue-300',
    outline: 'border border-blue-500 bg-transparent text-blue-500',
    soft: 'bg-blue-200 text-blue-500',
    minimal: 'bg-transparent text-blue-500',
  },
  orange: {
    text: 'text-orange-50',
    background: 'bg-orange-500',
    hover: 'hover:bg-orange-600',
    focus: 'focus:border-orange-200',
    disabled: 'disabled:bg-orange-300',
    outline: 'border border-orange-500 bg-transparent text-orange-500',
    soft: 'bg-orange-200 text-orange-500',
    minimal: 'bg-transparent text-orange-500',
  },
  red: {
    text: 'text-red-50',
    background: 'bg-red-500',
    hover: 'hover:bg-red-600',
    focus: 'focus:border-red-200',
    disabled: 'disabled:bg-red-300',
    outline: 'border border-red-500 bg-transparent text-red-500',
    soft: 'bg-red-200 text-red-500',
    minimal: 'bg-transparent text-red-500',
  },
};
